// <auto-generated />
namespace AssetTrackingSystem_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Branchnamenotunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Branchnamenotunique));
        
        string IMigrationMetadata.Id
        {
            get { return "201703061106143_Branch name not unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
